"""Explicit lifecycle graphs. External lifecycle states are modeled, not executed."""
from job_applier.models import ApplicationStatus as A, OutreachStatus as O

APPLICATION_TRANSITIONS = {
    A.DISCOVERED: {A.SHORTLISTED, A.BLOCKED, A.BLOCKED_UNKNOWN_QUESTION, A.CLOSED},
    A.SHORTLISTED: {A.READY_TO_APPLY, A.BLOCKED, A.BLOCKED_UNKNOWN_QUESTION, A.WITHDRAWN, A.CLOSED},
    A.READY_TO_APPLY: {A.SUBMITTED, A.SUBMISSION_FAILED, A.BLOCKED, A.BLOCKED_UNKNOWN_QUESTION, A.WITHDRAWN},
    A.BLOCKED: {A.SHORTLISTED, A.BLOCKED_UNKNOWN_QUESTION, A.WITHDRAWN, A.CLOSED},
    A.BLOCKED_UNKNOWN_QUESTION: {A.SHORTLISTED, A.BLOCKED, A.WITHDRAWN, A.CLOSED},
    # Failed/ambiguous submissions cannot be retried directly.
    A.SUBMISSION_FAILED: {A.SUBMISSION_UNCERTAIN},
    A.SUBMISSION_UNCERTAIN: set(),  # Dedicated evidence-backed human reconciliation only.
    A.CONFIRMED_NOT_SUBMITTED: set(),  # Dedicated human retry authorization only.
    A.SUBMITTED: {A.APPLICATION_RECEIVED, A.UNDER_REVIEW, A.RECRUITER_SCREEN, A.INTERVIEW, A.ASSESSMENT, A.REJECTED, A.WITHDRAWN, A.CLOSED},
    A.APPLICATION_RECEIVED: {A.UNDER_REVIEW, A.RECRUITER_SCREEN, A.INTERVIEW, A.ASSESSMENT, A.REJECTED, A.WITHDRAWN, A.CLOSED},
    A.UNDER_REVIEW: {A.RECRUITER_SCREEN, A.INTERVIEW, A.ASSESSMENT, A.REJECTED, A.WITHDRAWN, A.CLOSED},
    A.RECRUITER_SCREEN: {A.INTERVIEW, A.ASSESSMENT, A.FINAL_INTERVIEW, A.REJECTED, A.WITHDRAWN, A.CLOSED},
    A.INTERVIEW: {A.ASSESSMENT, A.FINAL_INTERVIEW, A.OFFER, A.REJECTED, A.WITHDRAWN, A.CLOSED},
    A.ASSESSMENT: {A.INTERVIEW, A.FINAL_INTERVIEW, A.OFFER, A.REJECTED, A.WITHDRAWN, A.CLOSED},
    A.FINAL_INTERVIEW: {A.OFFER, A.REJECTED, A.WITHDRAWN, A.CLOSED},
    A.OFFER: {A.WITHDRAWN, A.CLOSED},
    A.REJECTED: {A.CLOSED}, A.WITHDRAWN: {A.CLOSED}, A.CLOSED: set(),
}
OUTREACH_TRANSITIONS = {
    O.PERSON_DISCOVERED: {O.CONTACT_VERIFIED, O.BLOCKED, O.CLOSED},
    O.CONTACT_VERIFIED: {O.DRAFT_CREATED, O.BLOCKED, O.CLOSED},
    O.DRAFT_CREATED: {O.APPROVED, O.BLOCKED, O.CLOSED},
    O.APPROVED: {O.SENT, O.BLOCKED, O.CLOSED},
    O.SENT: {O.REPLIED, O.FOLLOW_UP_REQUIRED, O.CLOSED},
    O.REPLIED: {O.FOLLOW_UP_REQUIRED, O.CLOSED},
    O.FOLLOW_UP_REQUIRED: {O.DRAFT_CREATED, O.CLOSED},
    O.BLOCKED: {O.PERSON_DISCOVERED, O.CLOSED}, O.CLOSED: set(),
}


def validate_transition(previous: A | O, target: A | O) -> None:
    if type(previous) is not type(target):
        raise ValueError("State model mismatch")
    graph = APPLICATION_TRANSITIONS if isinstance(previous, A) else OUTREACH_TRANSITIONS
    if target not in graph[previous]:
        raise ValueError(f"Invalid transition: {previous.value} -> {target.value}")
